namespace: '{{ .Release.Namespace }}'
namePrefix: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-'

commonAnnotations:
  meta.helm.sh/release-name: '{{ .Release.Name }}'
  meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'

commonLabels:
  app.giantswarm.io/branch: '{{ .Values.project.branch }}'
  app.giantswarm.io/commit: '{{ .Values.project.commit }}'
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
  app.kubernetes.io/instance: '{{ .Release.Name }}'

images:
  - name: controller
    newName: "{{ .Values.registry.domain }}/{{ .Values.image.name }}"
    newTag: "{{ .Values.image.tag }}"
replicas:
  - name: controller-manager
    count: 3

resources:
  - ../default
  - manager_config.yaml

components:
  - ../components/psp

patchesStrategicMerge:
  - manager_patch.yaml
