namespace: '{{ .Release.Namespace }}'
namePrefix: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-'

commonAnnotations:
  meta.helm.sh/release-name: '{{ .Release.Name }}'
  meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'

# NOTE: Do not use commonLabels. LabelTransformer is configured explicitly
# instead so solve problems with selectors. It is defined in
# label_transformer.yaml.
#
#     See: https://github.com/kubernetes-sigs/kustomize/issues/1009
#
#commonLabels:

images:
  - name: controller
    newName: "{{ .Values.registry.domain }}/{{ .Values.image.name }}"
    newTag: "{{ .Values.image.tag }}"
replicas:
  - name: controller-manager
    count: 3

resources:
  - ../default
  - manager_config.yaml

components:
  - ../components/psp

patchesStrategicMerge:
  - manager_patch.yaml

transformers:
  - label_transformer.yaml
