
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-v1beta1-deployment
  failurePolicy: Fail
  name: vdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
- admissionReviewVersions:
  - v1
  - v1beta1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-security-giantswarm-io-v1alpha1-organization
  failurePolicy: Fail
  name: organization.security.giantswarm.io
  rules:
  - apiGroups:
    - security.giantswarm.io
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - organizations
