version: 2.1

orbs:
  architect: giantswarm/architect@2.4.2

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: management-cluster-admission
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-management-cluster-admission-to-docker
          image: "docker.io/giantswarm/management-cluster-admission"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-management-cluster-admission-to-quay
          image: "quay.io/giantswarm/management-cluster-admission"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-management-cluster-admission-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/management-cluster-admission"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-management-cluster-admission-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "management-cluster-admission"
          requires:
            - push-management-cluster-admission-to-quay
            - push-management-cluster-admission-to-docker
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-management-cluster-admission-to-aws-app-collection
          context: architect
          app_name: "management-cluster-admission"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-management-cluster-admission-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-management-cluster-admission-to-azure-app-collection
          context: architect
          app_name: "management-cluster-admission"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-management-cluster-admission-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-management-cluster-admission-to-kvm-app-collection
          context: architect
          app_name: "management-cluster-admission"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-management-cluster-admission-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
