version: 2.1

orbs:
  architect: giantswarm/architect@dev:new-gen-push-to-app-collection

workflows:
  build:
    jobs:
      - architect/push-to-app-collection:
          name: push-management-cluster-admission-to-pawel-collection
          context: architect
          app_name: "management-cluster-admission"
          app_namespace: "does-not-exist"
          app_collection_repo: "pawel-collection"
