version: 2.1

orbs:
  architect: giantswarm/architect@dev:overwrite-apps

workflows:
  build:
    jobs:

      - architect/push-to-app-collection:
          name: push-to-app-collection
          context: architect
          app_name: "management-cluster-admission"
          app_namespace: "giantswarm"
          app_collection_repo: "pawel-collection"
